### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mattcantstop** [jesford/git-implementation-in-python#1]
@jesford, thanks for your work to make this readable in Python. Over the past month I have overcommitted myself a few times and this was incredibly helpful and timely. A sincere thank you! 

![thank-you](https://user-images.githubusercontent.com/995208/27696575-3eaaf2fc-5caf-11e7-985f-c0ab95b3a570.gif)

**Comment by jesford** [comment]
Thank you @mattcantstop! That was fun and a really useful learning experience for me. I had no idea what was really in that .git folder :) Thanks for spending an evening with the PyLadies!
